memory_buffer_size: 10000
viewer_type: "static"

nidaq:
  device_name: "Dev1"
  lines: "port1/line0"
  ctr: "ctr0"
  io_type: "DO"
  widgets:
    - "nidaq_test"

encoder:
  type: "wheel"
  port: "COM4"
  baudrate: 57600
  cpr: 2400
  diameter_mm: 80
  sample_interval_ms: 20
  development_mode: False

cameras:
  - id: "dev"
    name: "devcam1"
    backend: "micromanager"
    micromanager_path: "C:/Program Files/Micro-Manager-2.0"
    viewer_type: "static"


  # - id: "dev"
  #   name: "devcam2"
  #   backend: "micromanager"
  #   micromanager_path: "C:/Program Files/Micro-Manager-thor"



  # - id: "arducam"
  #   name: "arducam"
  #   backend: "opencv"
  #   properties:
  #     fps: 30